export const NAV_LINKS = [
  { label: "Simulador", href: "/simulador" },
  { label: "Sobre", href: "/sobre" },
  { label: "Casting", href: "/casting" },
  { label: "Cases", href: "/cases" },
  { label: "Serviços", href: "/servicos" },
  { label: "Contato", href: "/contato" },
] as const;

export const SOCIAL_LINKS = [
  { platform: "Instagram", href: "https://instagram.com/seekmedia", icon: "instagram" },
  { platform: "TikTok", href: "https://tiktok.com/@seekmedia", icon: "tiktok" },
  { platform: "LinkedIn", href: "https://linkedin.com/company/seekmedia", icon: "linkedin" },
  { platform: "YouTube", href: "https://youtube.com/@seekmedia", icon: "youtube" },
] as const;

export const CLIENT_LOGOS: { name: string; src: string }[] = [
  { name: "Abradee", src: "/images/logos/Home-Logos-224x96-ABRADEE.png" },
  { name: "Amazon", src: "/images/logos/Home-Logos-224x96-AMAZON.png" },
  { name: "Ambev", src: "/images/logos/Home-Logos-224x96-AMBEV.png" },
  { name: "Bet4", src: "/images/logos/Home-Logos-224x96-BET4.png" },
  { name: "Bet7k", src: "/images/logos/Home-Logos-224x96-BET7K.png" },
  { name: "Beto Carrero", src: "/images/logos/Home-Logos-224x96-BETOCARRERO.png" },
  { name: "BIC", src: "/images/logos/Home-Logos-224x96-BIC.png" },
  { name: "Blaze", src: "/images/logos/Home-Logos-224x96-BLAZE.png" },
  { name: "Blizzard", src: "/images/logos/Home-Logos-224x96-BLIZZARD.png" },
  { name: "Campus Party", src: "/images/logos/Home-Logos-224x96-CAMPUSPARTY.png" },
  { name: "Chevrolet", src: "/images/logos/Home-Logos-224x96-CHEVROLET.png" },
  { name: "Claw Express", src: "/images/logos/Home-Logos-224x96-CLAWEXPRESS.png" },
  { name: "Clima Info", src: "/images/logos/Home-Logos-224x96-CLIMAINFO.png" },
  { name: "COC", src: "/images/logos/Home-Logos-224x96-COC.png" },
  { name: "Colgate", src: "/images/logos/Home-Logos-224x96-COLGATE.png" },
  { name: "Columbia Pictures", src: "/images/logos/Home-Logos-224x96-COLUMBIAPICTURES.png" },
  { name: "Disney", src: "/images/logos/Home-Logos-224x96-DISNEY.png" },
  { name: "Faber-Castell", src: "/images/logos/Home-Logos-224x96-FABERCASTELL.png" },
  { name: "Fortnite", src: "/images/logos/Home-Logos-224x96-FORTNITE.png" },
  { name: "Gillette", src: "/images/logos/Home-Logos-224x96-GILLETTE.png" },
  { name: "Google", src: "/images/logos/Home-Logos-224x96-GOOGLE.png" },
  { name: "Growth", src: "/images/logos/Home-Logos-224x96-GROWTH.png" },
  { name: "IBM", src: "/images/logos/Home-Logos-224x96-IBM.png" },
  { name: "Insider", src: "/images/logos/Home-Logos-224x96-INSIDER.png" },
  { name: "Itaú", src: "/images/logos/Home-Logos-224x96-ITAU.png" },
  { name: "JonBet", src: "/images/logos/Home-Logos-224x96-JONBET.png" },
  { name: "LATAM", src: "/images/logos/Home-Logos-224x96-LATAM.png" },
  { name: "Localiza", src: "/images/logos/Home-Logos-224x96-LOCALIZA.png" },
  { name: "LuckBet", src: "/images/logos/Home-Logos-224x96-LUCKBET.png" },
  { name: "Manual", src: "/images/logos/Home-Logos-224x96-MANUAL.png" },
  { name: "NET", src: "/images/logos/Home-Logos-224x96-NET.png" },
  { name: "Netflix", src: "/images/logos/Home-Logos-224x96-NETFLIX.png" },
  { name: "Nextel", src: "/images/logos/Home-Logos-224x96-NEXTEL.png" },
  { name: "Nickelodeon", src: "/images/logos/Home-Logos-224x96-NICKELODEON.png" },
  { name: "Nomad", src: "/images/logos/Home-Logos-224x96-NOMAD.png" },
  { name: "Olá Doutor", src: "/images/logos/Home-Logos-224x96-OLADOUTOR.png" },
  { name: "Olimpíada de Empreendedorismo", src: "/images/logos/Home-Logos-224x96-OLIMPIADADEEMPREENDEDORISMO.png" },
  { name: "Paramount", src: "/images/logos/Home-Logos-224x96-PARAMOUNT.png" },
  { name: "Pfizer", src: "/images/logos/Home-Logos-224x96-PFIZER.png" },
  { name: "Pichau", src: "/images/logos/Home-Logos-224x96-PICHAU.png" },
  { name: "Rocketseat", src: "/images/logos/Home-Logos-224x96-ROCKETSEAT.png" },
  { name: "SBT", src: "/images/logos/Home-Logos-224x96-SBT.png" },
  { name: "Skeelo", src: "/images/logos/Home-Logos-224x96-Home-Logos-224x96-SKEELO.png" },
  { name: "SENAC", src: "/images/logos/Home-Logos-224x96-SENAC.png" },
  { name: "Solana", src: "/images/logos/Home-Logos-224x96-SOLANA.png" },
  { name: "Taxation MID", src: "/images/logos/Home-Logos-224x96-Home-Logos-224x96-TAXATIONMID.png" },
  { name: "Telecine", src: "/images/logos/Home-Logos-224x96-TELECINE.png" },
  { name: "Trident", src: "/images/logos/Home-Logos-224x96-TRIDENT.png" },
  { name: "Universal", src: "/images/logos/Home-Logos-224x96-UNIVERSAL.png" },
  { name: "Veroo", src: "/images/logos/Home-Logos-224x96-VEROO.png" },
  { name: "Visa", src: "/images/logos/Home-Logos-224x96-VISA.png" },
  { name: "Warner Bros", src: "/images/logos/Home-Logos-224x96-WARNERBROS.png" },
  { name: "World", src: "/images/logos/Home-Logos-224x96-WORLD.png" },
  { name: "Xcaret México", src: "/images/logos/Home-Logos-224x96-XCARETMEXICO.png" },
];

// FEATURED_INFLUENCERS is defined after ALL_INFLUENCERS (see below)

export const COUNTERS = [
  { value: 17.9, suffix: "M+", label: "Alcance em Impressões", decimals: 1 },
  { value: 10, suffix: "+", label: "Anos de Experiência" },
  { value: 500, suffix: "+", label: "Impactos Gerados" },
];

export const FEATURED_CASES = [
  {
    brand: "Nike",
    slug: "nike-lancamento-chuteiras",
    influencer: "Ronaldinho Gaúcho",
    result: "2M views em 24h",
    description: "Campanha de lançamento da nova linha de chuteiras com conteúdo exclusivo para Instagram e TikTok.",
    metric: "2M",
    metricLabel: "views em 24h",
  },
  {
    brand: "Natura",
    slug: "natura-beleza-natural",
    influencer: "Juliette Freire",
    result: "+340% engajamento",
    description: "Série de conteúdos sobre beleza natural que gerou recorde de engajamento para a marca.",
    metric: "+340%",
    metricLabel: "engajamento",
  },
  {
    brand: "iFood",
    slug: "ifood-live-commerce",
    influencer: "Casimiro Miguel",
    result: "5M impressões",
    description: "Ação de live commerce com integração direta ao app, gerando conversões em tempo real.",
    metric: "5M",
    metricLabel: "impressões",
  },
];

export const SERVICES = [
  {
    title: "Gestão de Influenciadores",
    description: "Seleção, curadoria e gestão completa de campanhas com os maiores criadores do Brasil. Do briefing ao relatório final.",
    icon: "users",
    longDescription: "Nossa equipe especializada cuida de todo o processo: desde a identificação dos criadores ideais para sua marca, passando pela negociação e briefing, até o acompanhamento da produção e entrega dos relatórios de performance. Com um casting de mais de 500 influenciadores ativos, encontramos o match perfeito para cada campanha.",
    features: ["Curadoria personalizada de influenciadores", "Negociação e contratos", "Briefing e acompanhamento criativo", "Relatórios de performance detalhados"],
  },
  {
    title: "Produção Audiovisual",
    description: "Direção criativa, filmagem, edição e pós-produção. Conteúdos que capturam atenção e geram resultados.",
    icon: "video",
    longDescription: "Produzimos conteúdo de alta qualidade para todas as plataformas. Nossa equipe de produção conta com diretores criativos, cinegrafistas, editores e motion designers que entendem a linguagem de cada rede social e formato de conteúdo.",
    features: ["Direção criativa e roteiro", "Filmagem profissional", "Edição e pós-produção", "Motion design e animação"],
  },
  {
    title: "Projetos Especiais",
    description: "Eventos, ativações, collabs exclusivas e projetos sob medida que conectam marcas e criadores de forma única.",
    icon: "strategy",
    longDescription: "Criamos experiências memoráveis que vão além do digital. De eventos presenciais a ativações de marca, collabs entre criadores e lançamentos exclusivos — cada projeto é desenhado sob medida para gerar impacto real e conexões autênticas entre marcas e seus públicos.",
    features: ["Eventos e ativações de marca", "Collabs exclusivas entre criadores", "Lançamentos e campanhas especiais", "Experiências imersivas e inovadoras"],
  },
];

export const TEAM_MEMBERS = [
  { name: "Ana Silva", role: "CEO & Fundadora", bio: "15 anos de experiência em marketing digital e influência." },
  { name: "Carlos Mendes", role: "Diretor Criativo", bio: "Ex-diretor de conteúdo em grandes agências de publicidade." },
  { name: "Mariana Costa", role: "Head de Casting", bio: "Especialista em curadoria e gestão de talentos digitais." },
  { name: "Rafael Santos", role: "Head de Produção", bio: "Cinegrafista e editor com passagem por grandes emissoras." },
];

export const VALUES = [
  { title: "Autenticidade", description: "Acreditamos em conexões reais entre marcas e criadores. Cada campanha reflete a verdade da marca e do influenciador." },
  { title: "Resultados", description: "Não buscamos apenas números — buscamos impacto real. Cada métrica é acompanhada de perto para garantir performance." },
  { title: "Inovação", description: "Estamos sempre à frente das tendências. Testamos novos formatos, plataformas e abordagens para manter sua marca relevante." },
  { title: "Transparência", description: "Relatórios claros, comunicação aberta e processos documentados. Você sabe exatamente o que está acontecendo." },
];

export const CASTING_FILTERS = {
  niches: ["Todos", "Esporte", "Lifestyle", "Humor", "Beleza", "Moda", "Entretenimento", "Música", "Tech", "Gastronomia", "Fitness"],
  platforms: ["Todas", "Instagram", "TikTok", "YouTube", "Twitter"],
  sizes: ["Todos", "Nano (10-50K)", "Micro (50-500K)", "Médio (500K-1M)", "Macro (1-10M)", "Mega (10M+)"],
};

import type { Influencer } from "./types";

export const ALL_INFLUENCERS: Influencer[] = [
  { order: 1,  name: "Ronaldinho Gaúcho",              handle: "@ronaldinho",              slug: "ronaldinho-gaucho",     niches: ["Esporte", "Futebol"],                              followers: "155.3M", engagement: "",      platforms: ["Instagram", "TikTok", "YouTube"],         color: "#00F0D0", badges: ["Top of mind"], photoUrl: "/images/influencers/ronaldinho.jpg",        bio: "Ícone do futebol mundial, 2x Melhor Jogador do Mundo pela FIFA, Pentacampeão Mundial. Embaixador do Esporte, Desenvolvimento e Paz pela ONU." },
  { order: 2,  name: "Você Sabia?",                    handle: "@vocesabiavideo",          slug: "voce-sabia",            niches: ["Curiosidades", "Educação"],                        followers: "76.3M",  engagement: "",      platforms: ["YouTube", "Instagram"],                   color: "#80F090", badges: ["Top of mind"], photoUrl: "",                                          bio: "Pioneiro na internet, produz conteúdo variado adaptado para qualquer segmento. Maior canal do mundo nas categorias Curiosidades e Educação. 8.1 bilhões de views no YouTube." },
  { order: 3,  name: "Luva de Pedreiro",               handle: "@luvadepedreiro",          slug: "luva-de-pedreiro",      niches: ["Futebol", "Entretenimento"],                       followers: "53M",    engagement: "",      platforms: ["Instagram", "TikTok"],                    color: "#D0F060", badges: ["Top of mind"], photoUrl: "/images/influencers/luvadepedreiro.jpg",    bio: "Maior influencer de futebol do mundo. Primeiro brasileiro seguido pela conta oficial do Instagram. 729 milhões de views em Instagram Reels." },
  { order: 4,  name: "Juju Salimeni",                  handle: "@jujusalimeni",            slug: "juju-salimeni",         niches: ["Fitness", "Vlog", "Lifestyle"],                    followers: "20M",    engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#E0F050", badges: [],             photoUrl: "/images/influencers/jujusalimeni.jpg",     bio: "Nome forte na internet e na TV aberta. Proprietária da Shine Skin e sócia da academia Ironberg. Eleita a Mulher mais sexy do mundo em 2010." },
  { order: 5,  name: "Pyong Lee",                      handle: "@pyonglee",                slug: "pyong-lee",             niches: ["Hipnose", "Mágico", "Vlog"],                       followers: "20M",    engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/pyong.jpg",            bio: "O mágico mais seguido do mundo e maior canal de hipnose do mundo. Ganhou mais visibilidade ao participar do BBB 20." },
  { order: 6,  name: "EiNerd",                         handle: "@einerd.com.br",           slug: "einerd",                niches: ["Animes", "Entretenimento", "Cultura Pop"],         followers: "18.8M",  engagement: "",      platforms: ["YouTube", "Instagram"],                   color: "#80F090", badges: ["Destaque"],    photoUrl: "/images/influencers/einerd.jpg",           bio: "Canal de entretenimento e cultura pop que conecta milhões de fãs apaixonados no Brasil. 316 milhões de impressões mensais." },
  { order: 7,  name: "LuCão",                          handle: "@lucaoreal",               slug: "lucao",                 niches: ["Humor", "Pegadinhas", "Entretenimento"],           followers: "15M",    engagement: "",      platforms: ["Instagram", "YouTube", "TikTok"],         color: "#D0F060", badges: [],             photoUrl: "/images/influencers/lucao.jpg",            bio: "Criador da Roleta Solidária. Conteúdo marcado por interações reais nas ruas. +400 milhões de views na Roleta e 1 bilhão de views totais." },
  { order: 8,  name: "Jon Vlogs",                      handle: "@jonvlogs",                slug: "jon-vlogs",             niches: ["IRL", "Vlogs", "Entretenimento"],                  followers: "14.7M",  engagement: "",      platforms: ["YouTube", "Instagram", "Twitch"],         color: "#E0F050", badges: [],             photoUrl: "/images/influencers/jonvlogs.jpg",         bio: "Iniciou sua jornada digital em 2015 compartilhando sua rotina como estudante de intercâmbio nos EUA. Presidente do CAPIM FC. 5 milhões de horas assistidas." },
  { order: 9,  name: "Jornada Top",                    handle: "@jornadatop",              slug: "jornada-top",           niches: ["Tecnologia", "Dicas", "Inovação"],                 followers: "—",      engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/jornadatop.jpg",       bio: "Vencedor do Prêmio iBest 2023 (Melhor influencer: Inovação e Tecnologia). Conteúdo tutorial e educativo sobre gadgets e inovação. Média de 500 mil views por publicação." },
  { order: 10, name: "Danilo Gentili",                 handle: "@danilogentili",           slug: "danilo-gentili",        niches: ["Apresentador", "Entretenimento"],                  followers: "—",      engagement: "",      platforms: ["YouTube", "Instagram"],                   color: "#80F090", badges: ["Em alta"],    photoUrl: "/images/influencers/danilogentili.jpg",   bio: "Um dos principais nomes do entretenimento brasileiro. Apresentador do The Noite. 408 milhões de views no YouTube no 1º semestre de 2025." },
  { order: 11, name: "Craque Neto",                    handle: "@10neto",                  slug: "craque-neto",           niches: ["Apresentador", "Esporte"],                         followers: "11.4M",  engagement: "",      platforms: ["YouTube", "Instagram"],                   color: "#D0F060", badges: [],             photoUrl: "/images/influencers/craqueneto.jpg",      bio: "Ex-jogador profissional, comentarista e apresentador. Lenda do Corinthians e da TV aberta. 433 milhões de views no YouTube e +1 bilhão em todas as plataformas." },
  { order: 12, name: "Carlos Massa (Ratinho)",         handle: "@oratinho",                slug: "ratinho",               niches: ["Apresentador", "Popular"],                         followers: "8.7M",   engagement: "",      platforms: ["Instagram"],                              color: "#E0F050", badges: [],             photoUrl: "/images/influencers/ratinho.jpg",         bio: "Apresentador do Programa do Ratinho no SBT. Programa atingiu 84 milhões de espectadores no ano. Melhor comunicador do ano (Prêmio Área Vip 2024 e 2025)." },
  { order: 13, name: "Professor Noslen",               handle: "@professornoslen",         slug: "professor-noslen",      niches: ["Educação", "Língua Portuguesa"],                   followers: "—",      engagement: "",      platforms: ["YouTube", "Instagram"],                   color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/noslen.jpg",          bio: "Maior canal do mundo de ensino de língua portuguesa no YouTube. Transforma o ensino de Português e Literatura em experiência leve e acessível. 400 milhões de views." },
  { order: 14, name: "Inteligência Ltda",              handle: "@inteligencialtda",        slug: "inteligencia-ltda",     niches: ["Podcast", "Entretenimento", "Cultura"],            followers: "7M",     engagement: "",      platforms: ["YouTube", "Instagram", "Spotify"],        color: "#80F090", badges: ["Destaque"],    photoUrl: "/images/influencers/inteligenciaLTDA.jpg", bio: "Top 5 podcasts do Brasil. +1.576 episódios. +880 milhões de views no YouTube. Listado entre os 2% mais populares do mundo entre +3.5 milhões de podcasts." },
  { order: 15, name: "Weedzão",                        handle: "@weedzao",                 slug: "weedzao",               niches: ["Viagens", "E-Sports", "Gameplay"],                 followers: "—",      engagement: "",      platforms: ["YouTube", "Instagram"],                   color: "#D0F060", badges: [],             photoUrl: "",                                         bio: "Bi-Campeão Mundial de Free Fire. Embaixador do time de eSports do Flamengo e também jogou pelo Corinthians. +268.2 milhões de views." },
  { order: 16, name: "Mari Borges",                    handle: "@mariiborges._",           slug: "mari-borges",           niches: ["Lifestyle", "Moda", "Humor"],                      followers: "3.5M",   engagement: "2.45%", platforms: ["TikTok", "Instagram"],                    color: "#E0F050", badges: ["Em alta"],    photoUrl: "/images/influencers/mariborges.jpg",      bio: "Compartilha vídeos de moda, dança, desafios, humor e interação social. Fundadora da NUWA, marca de roupas. +348 milhões de views. Crescimento de 578%." },
  { order: 17, name: "Renata Fan",                     handle: "@renatafan",               slug: "renata-fan",            niches: ["Apresentadora", "Esporte"],                        followers: "—",      engagement: "",      platforms: ["YouTube", "Instagram"],                   color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/renatafan.jpg",       bio: "Apresentadora do Jogo Aberto (Rede Bandeirantes). Ex-Miss Brasil 1999. 689 milhões de views no YouTube. Média de 922 mil views por Reels no Instagram." },
  { order: 18, name: "Bambam",                         handle: "@bambamoficial",           slug: "bambam",                niches: ["Fitness", "Lifestyle", "Humor"],                   followers: "5.8M",   engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#80F090", badges: [],             photoUrl: "/images/influencers/bambam.jpg",          bio: "Campeão do primeiro BBB. Campeão de fisiculturismo em Las Vegas (2018). Participante do Fight Music Show. Host do Bambam Podcast. Há 22 anos na mídia." },
  { order: 19, name: "Thiago Sem T",                   handle: "@thiagosemt",              slug: "thiago-sem-t",          niches: ["Humor", "Popular"],                                followers: "5.7M",   engagement: "6.11%", platforms: ["YouTube", "Instagram"],                   color: "#D0F060", badges: [],             photoUrl: "",                                         bio: "Criador de conteúdo de humor direto e cotidiano. 266 milhões de views no YouTube. Taxa de engajamento muito acima da média (6.11%). Collabs com Danilo Gentili e outros grandes nomes." },
  { order: 20, name: "Nerds de Negócios",              handle: "@nerdsdenegociosoficial",  slug: "nerds-de-negocios",     niches: ["Educação", "Empreendedorismo"],                    followers: "5.4M",   engagement: "",      platforms: ["YouTube", "Instagram"],                   color: "#E0F050", badges: [],             photoUrl: "/images/influencers/nerddenegocios.jpg",  bio: "Canal criado para ensinar a comunidade a rentabilizar trabalhando com internet. +20 anos de experiência como empreendedor e comunicador. 160 milhões de views." },
  { order: 21, name: "Eduardo Feldberg (Primo Pobre)", handle: "@eduardofeldberg",         slug: "eduardo-feldberg",      niches: ["Dicas", "Finanças", "Humor"],                      followers: "2.8M",   engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/primopobre.jpg",      bio: "Criador do Podcast Pobre Show. +148 milhões de views. Aborda finanças de forma descomplicada e sincera. Autor de livro bestseller #1 na Amazon." },
  { order: 22, name: "Juliane Coura",                  handle: "@juliane.coura",           slug: "juliane-coura",         niches: ["Empreendedorismo", "Fitness", "Humor"],            followers: "2.6M",   engagement: "1.78%", platforms: ["TikTok", "Instagram"],                    color: "#80F090", badges: ["Em alta"],    photoUrl: "/images/influencers/julianecoura.jpg",    bio: "Fenômeno de visualizações. Sketches de humor virais. Perfil multifacetado que transita entre diferentes públicos. +3 bilhões de views. Crescimento de 46.87%." },
  { order: 23, name: "Éricka Leite",                   handle: "@erickaleiteb",            slug: "ericka-leite",          niches: ["Relacionamentos", "Lifestyle", "Viagem"],          followers: "4M",     engagement: "",      platforms: ["Instagram"],                              color: "#D0F060", badges: [],             photoUrl: "/images/influencers/erickaleite.jpg",     bio: "Socialite. Conteúdo de moda, viagens e cotidiano de um casal bem-sucedido. +18.4 milhões de views. Publicações vistas por ~10.12% dos seguidores." },
  { order: 24, name: "Maumauzk",                       handle: "@maumauzk",                slug: "maumauzk",              niches: ["Vlog", "Lifestyle", "Humor"],                      followers: "2.8M",   engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#E0F050", badges: [],             photoUrl: "/images/influencers/maumau.jpg",          bio: "Conecta públicos diferentes. Descoberto através do Free Fire. +332.6 milhões de views. Taxa de engajamento muito acima da média." },
  { order: 25, name: "Matheus Tomoto",                 handle: "@matheustomoto",           slug: "matheus-tomoto",        niches: ["Educação", "Intercâmbio"],                         followers: "—",      engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/matheustomoto.jpg",   bio: "Forbes 30 Under 30. Formado em escola pública, conquistou bolsas em Harvard, MIT e Stanford. Capacitou 12 mil alunos a estudarem fora do país com bolsa de estudos." },
  { order: 26, name: "Gaba",                           handle: "@gabrielbruno",            slug: "gaba",                  niches: ["Entretenimento", "Dicas", "Gastronomia"],          followers: "2.4M",   engagement: "6.04%", platforms: ["YouTube", "Instagram"],                   color: "#80F090", badges: [],             photoUrl: "/images/influencers/gaba.jpg",            bio: "Reviews de restaurantes, bares e afins. Engajamento maior que 90% dos YouTubers de tamanho semelhante. Média de 395.5k views no Instagram. Fundador da Leal Lanches." },
  { order: 27, name: "Diguinho Coruja",                handle: "@diguinhocoruja",          slug: "diguinho-coruja",       niches: ["Humor", "Popular"],                                followers: "2.3M",   engagement: "2.67%", platforms: ["Instagram", "YouTube"],                   color: "#D0F060", badges: [],             photoUrl: "/images/influencers/diguinhocoruja.jpg",  bio: "Radialista e humorista. Troféu APCA 2013 (Humor). Integra o elenco do The Noite (SBT). 1 bilhão de views acumuladas no YouTube pelo The Noite." },
  { order: 28, name: "Tecnosh",                        handle: "@tecnoshlol",              slug: "tecnosh",               niches: ["Streamer", "Games", "Tecnologia"],                 followers: "273K",   engagement: "",      platforms: ["Twitch", "YouTube", "Instagram"],         color: "#E0F050", badges: [],             photoUrl: "",                                         bio: "Streamer de Games e Tecnologia. Pico de audiência de 40.7 mil na Twitch. Engajamento maior que 86% dos influencers de tamanho semelhante." },
  { order: 29, name: "Dani Molo",                      handle: "@danimolo",                slug: "dani-molo",             niches: ["E-Sports", "Gaming", "Entretenimento"],            followers: "2.4M",   engagement: "",      platforms: ["YouTube", "Instagram", "TikTok"],         color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/danimolo.jpg",        bio: "Co-fundador do canal Você Sabia? (74.2M seguidores). Co-fundador do Magic Squad (time de Free Fire campeão mundial 2023). Co-fundador da label de música Tropa do Bruxo." },
  { order: 30, name: "Tatiana Frazão",                 handle: "@frazoniss",               slug: "tatiana-frazao",        niches: ["Viagens", "Lifestyle", "Humor"],                   followers: "1.7M",   engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#80F090", badges: [],             photoUrl: "/images/influencers/tatianafrazao.jpg",   bio: "Compartilha fatos interessantes e divertidos do cotidiano com bom humor. Fundadora da marca UZFRAN. +208 milhões de views." },
  { order: 31, name: "Msvilla (Ketlin Gro)",           handle: "@ketlingro_",              slug: "ketlingro",             niches: ["Fitness", "Adulto", "Humor"],                      followers: "2.1M",   engagement: "",      platforms: ["Instagram"],                              color: "#D0F060", badges: [],             photoUrl: "/images/influencers/ketlingroisman.jpg",  bio: "Criadora de conteúdo adulto, alcançando Top 1 na plataforma Privacy. Conteúdo de humor nas plataformas digitais. Participante da Mansão Maromba." },
  { order: 32, name: "Luizo Mesquita",                 handle: "@luizomesquita",           slug: "luizo-mesquita",        niches: ["Calistenia", "Fitness"],                           followers: "1.9M",   engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#E0F050", badges: [],             photoUrl: "/images/influencers/luizmesquita.jpg",    bio: "Multiatleta, filho do Otávio Mesquita. Bi-campeão do Fight Music Show. Dissemina a prática da Calistenia gerando visibilidade e influência." },
  { order: 33, name: "Baiano (LOL)",                   handle: "@baianolol",               slug: "baiano-lol",            niches: ["E-Sports", "Geek", "Cultura Pop"],                 followers: "—",      engagement: "",      platforms: ["Twitch", "YouTube"],                      color: "#00F0D0", badges: ["Destaque"],    photoUrl: "/images/influencers/baianolol.jpg",       bio: "Principal nome do League of Legends no Brasil. Criador do Ilha das Lendas. 437 milhões de horas assistidas. 2º maior canal do mundo sobre LoL. Personalidade do ano 2023 (Prêmio Esports)." },
  { order: 34, name: "Yetz",                           handle: "@yetz",                    slug: "yetz",                  niches: ["Streamer", "Tecnologia", "Games"],                 followers: "930K",   engagement: "",      platforms: ["Twitch", "YouTube", "Instagram"],         color: "#80F090", badges: [],             photoUrl: "",                                         bio: "Streamer de Games e Tecnologia. +287 milhões de views. Engajamento maior que 94% dos influencers de tamanho semelhante. Ex-jogador profissional de League of Legends (Luminosity Gaming)." },
  { order: 35, name: "Bianca Witzel",                  handle: "@biancawitzel.s",          slug: "bianca-witzel",         niches: ["Educação", "Curiosidades", "Biologia"],            followers: "1.3M",   engagement: "3.10%", platforms: ["TikTok", "Instagram"],                    color: "#D0F060", badges: ["Em alta"],    photoUrl: "/images/influencers/biancawitzel.jpg",    bio: "Conhecida por divulgar curiosidades científicas, visitas a laboratórios e zoológicos. Inspira jovens mulheres a se interessarem pela ciência. Mencionada pela Folha de S.Paulo." },
  { order: 36, name: "Mylon (Milionzete)",             handle: "@mylonzete",               slug: "mylon-milionzete",      niches: ["E-Sports", "Geek", "Cultura Pop"],                 followers: "1.5M",   engagement: "",      platforms: ["YouTube", "Instagram"],                   color: "#E0F050", badges: [],             photoUrl: "/images/influencers/mylon.jpg",           bio: "Campeão brasileiro de LoL aos 15 anos. 3x Campeão de LoL. Co-host do 'Depois do Crime'. Cobertura do CBLOL no Ilha das Lendas. Cria conteúdo ensinando League of Legends no YouTube." },
  { order: 37, name: "Gustavo Minerva",                handle: "@gustavominerva",          slug: "gustavo-minerva",       niches: ["E-Sports", "Cultura Pop", "Geek"],                 followers: "1.5M",   engagement: "",      platforms: ["YouTube", "Instagram", "Twitch"],         color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/minerva.jpg",         bio: "Minerva jogou LoL profissionalmente por 9 anos (Kabum, Pain Gaming, Vivo Keyd, Rensga e Furia). Quadro 'Gossip da Semana' no IDL. +4 milhões de horas assistidas." },
  { order: 38, name: "AXT",                            handle: "@axtlol",                  slug: "axt",                   niches: ["Streamer", "Tecnologia", "Games"],                 followers: "900K",   engagement: "",      platforms: ["Twitch", "YouTube", "Instagram"],         color: "#80F090", badges: [],             photoUrl: "/images/influencers/axt.jpg",             bio: "Streamer de Games e Tecnologia. Pico de audiência de 50.7 mil na Twitch. Engajamento maior que 95% dos influencers de tamanho semelhante. Representou a América do Sul. Campeão Mundial de PUBG." },
  { order: 39, name: "Stereonline",                    handle: "@stereonline",             slug: "stereonline",           niches: ["Automobilismo", "Entretenimento", "Games"],        followers: "696K",   engagement: "",      platforms: ["Twitch", "YouTube", "Instagram"],         color: "#D0F060", badges: [],             photoUrl: "/images/influencers/stereonline.jpg",     bio: "Streamer de games de automobilismo. Também faz conteúdo ligado ao tema na vida real: Kart, Drift, Trilha de moto. Pico de audiência de 8 mil na Twitch. +100 milhões de views." },
  { order: 40, name: "Laiane Bernardes (Italiazeta)",  handle: "@laianeitalia",            slug: "laiane-bernardes",      niches: ["Moda", "Streamer", "Lifestyle"],                   followers: "552K",   engagement: "",      platforms: ["Twitch", "Instagram", "YouTube"],         color: "#E0F050", badges: [],             photoUrl: "/images/influencers/laianeitalia.jpg",    bio: "Influenciadora Stream focada em moda e lifestyle. 43.6 milhões de views no Instagram. Pico de audiência de 7.786 mil na Twitch." },
  { order: 41, name: "Gari Araras",                    handle: "@gari_araras_sp_oficial",  slug: "gari-araras",           niches: ["Viral", "Inspirador", "Fitness"],                  followers: "—",      engagement: "",      platforms: ["Instagram"],                              color: "#00F0D0", badges: ["Em alta"],    photoUrl: "/images/influencers/gariararassp.jpg",    bio: "Primeiro influencer Gari do Instagram. +90 milhões de contas conectadas. Fenômeno na internet com Reels com dezenas de milhões de visualizações." },
  { order: 42, name: "Esa Carry",                      handle: "@esacarry",                slug: "esa-carry",             niches: ["E-Sports", "Cultura Pop", "Geek"],                 followers: "935K",   engagement: "",      platforms: ["YouTube", "Twitch", "Instagram"],         color: "#80F090", badges: [],             photoUrl: "/images/influencers/esa.jpg",             bio: "Ex-jogador de LoL, atuou no cenário profissional de 2013 a 2020. Nasceu em Kakegawa, Japão. Co-host do 'Depois do Crime'. Cobertura do CBLOL no Ilha das Lendas." },
  { order: 43, name: "Matheus Pessanha",               handle: "@mathpessanha",            slug: "matheus-pessanha",      niches: ["Educação Musical", "Lifestyle", "Música"],        followers: "565K",   engagement: "",      platforms: ["Instagram", "TikTok"],                    color: "#D0F060", badges: [],             photoUrl: "/images/influencers/matheuspessanha.jpg", bio: "Talentoso cantor e multi-instrumentista. Mistura a tradição do samba com a inovação contemporânea. +11 milhões de views no Instagram. Crescimento de 807.46% na conta." },
  { order: 44, name: "Ranger",                         handle: "@rangerlol1",              slug: "ranger-lol",            niches: ["E-Sports", "Cultura Pop", "Geek"],                 followers: "700K",   engagement: "",      platforms: ["YouTube", "Twitch", "Instagram"],         color: "#E0F050", badges: [],             photoUrl: "/images/influencers/ranger.jpg",          bio: "Ex-jogador profissional de LoL. Figura icônica pelo jeito honesto de falar sobre times e jogadores. Co-host do 'Depois do Crime'. +362 mil horas assistidas." },
  { order: 45, name: "Marcio Lucas",                   handle: "@marciolucas10",           slug: "marcio-lucas",          niches: ["Desenvolvimento Pessoal", "Moda", "Etiqueta"],     followers: "—",      engagement: "",      platforms: ["Instagram", "TikTok"],                    color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/marciolucas.jpg",     bio: "Ajuda seu público a construir uma imagem mais forte e elegante. Foco em boas maneiras, etiqueta e desenvolvimento pessoal. +90 milhões de views. Crescimento de 412%." },
  { order: 46, name: "Julia Nunes",                    handle: "@julianunesbarboza",       slug: "julia-nunes",           niches: ["Fitness", "Relacionamento"],                       followers: "562K",   engagement: "",      platforms: ["Instagram"],                              color: "#80F090", badges: [],             photoUrl: "/images/influencers/julianunes.jpg",      bio: "Criadora de conteúdo sobre relacionamento, comunicação e autoestima. +44 milhões de views. 78x o número de seguidores em visualizações." },
  { order: 47, name: "Tay",                            handle: "@taylolxd1",               slug: "tay-lol",               niches: ["E-Sports", "Cultura Pop", "Geek"],                 followers: "463K",   engagement: "",      platforms: ["YouTube", "Twitch", "Instagram"],         color: "#D0F060", badges: [],             photoUrl: "/images/influencers/tay.jpg",             bio: "Ex-jogador profissional de LoL com 18 temporadas consecutivas. 2x Campeão Brasileiro de LoL. Cobertura recorrente da LCK e LPL pela Ilha das Lendas." },
  { order: 48, name: "Brucer",                         handle: "@brucerlol",               slug: "brucer-lol",            niches: ["E-Sports", "Geek", "Cultura Pop"],                 followers: "310K",   engagement: "",      platforms: ["YouTube", "Twitch", "Instagram"],         color: "#E0F050", badges: [],             photoUrl: "/images/influencers/brucer.jpg",          bio: "Ex-jogador profissional de LoL. 1x Campeão Brasileiro (Team One, 2017). Cobertura do CBLOL Academy e LCS. +560 mil horas assistidas." },
  { order: 49, name: "Soneca Roxx",                    handle: "@sonecaroxx",              slug: "soneca-roxx",           niches: ["Crypto Gaming", "Cassino Online", "Criptomoedas"], followers: "189K",  engagement: "",      platforms: ["YouTube", "Twitch", "Instagram", "Kick"], color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/sonecarox.jpg",      bio: "Pioneiro em jogos cripto. Conhecido por lives de cassino online. Skin in the game: utiliza seu próprio capital nos jogos ao vivo. 1.554.926 visualizações no YouTube." },
  { order: 50, name: "Jime",                           handle: "@jimelol1",                slug: "jime-lol",              niches: ["E-Sports", "Cultura Pop", "Geek"],                 followers: "180K",   engagement: "",      platforms: ["YouTube", "Twitch", "Instagram"],         color: "#80F090", badges: [],             photoUrl: "/images/influencers/jime.jpg",            bio: "Bárbara Prado, ex-jogadora profissional de LoL. Vencedora do GIRLGAMER Esports Festival (América do Sul, 2019). Disputou CBLOL Academy pela Red Canids (2022)." },
  { order: 51, name: "Magic Squad GG",                 handle: "@magicsquad_gg",           slug: "magic-squad-gg",        niches: ["E-Sports", "Free Fire", "Gaming"],                 followers: "100K",   engagement: "",      platforms: ["Instagram", "YouTube"],                   color: "#D0F060", badges: ["Destaque"],    photoUrl: "/images/influencers/magicsquad.jpg",      bio: "Time de E-Sports Campeão Mundial do Free Fire. Co-fundado por Dani Molo (Você Sabia). Ronaldinho Gaúcho é embaixador do projeto." },
  { order: 52, name: "Rahkys",                         handle: "@rahkyslol",               slug: "rahkys-lol",            niches: ["E-Sports", "Cultura Pop", "Geek"],                 followers: "50K",    engagement: "",      platforms: ["YouTube", "Twitch", "Instagram"],         color: "#E0F050", badges: [],             photoUrl: "/images/influencers/rahkys.jpg",          bio: "Leticia Soragni, ex-jogadora profissional de LoL. Bicampeã do torneio Ignis Cup. Desenvolve conteúdos informativos sobre LoL e faz parte das costreams de LCK e LPL." },
  { order: 53, name: "AMD (Amanda Abreu)",             handle: "@amd22k",                  slug: "amd-amanda-abreu",      niches: ["E-Sports", "Entretenimento", "Tecnologia"],        followers: "21.2K",  engagement: "1.21%", platforms: ["Twitch", "Instagram"],                    color: "#00F0D0", badges: [],             photoUrl: "/images/influencers/amandaamd.jpg",       bio: "Ex-jogadora profissional de Counter-Strike. Única mulher a ter uma skin em sua homenagem dentro do jogo. Caster de E-sports. Engajamento maior que 65% dos influencers de tamanho semelhante." },
  { order: 54, name: "Accez (Lucas Miranda)",          handle: "@accezlol",                slug: "accez-lol",             niches: ["E-Sports", "Cultura Pop", "Geek"],                 followers: "—",      engagement: "",      platforms: ["YouTube", "Twitch", "Instagram"],         color: "#80F090", badges: [],             photoUrl: "/images/influencers/accez.jpg",           bio: "Ex-jogador profissional de LoL, campeão do CBLOL Academy pela paiN Gaming. Streamer da IDL. Comenta e analisa partidas de LCK, LPL e outras ligas durante costreams do coletivo." },
  { order: 55, name: "Witold Ramasuskas",              handle: "@witold_113",              slug: "witold-ramasuskas",     niches: ["Automobilismo", "Lifestyle"],                      followers: "—",      engagement: "",      platforms: ["Instagram"],                              color: "#D0F060", badges: [],             photoUrl: "",                                         bio: "4x Campeão AMG Cup Brasil. 6x Campeão Paulista de Automobilismo. Vice-Campeão NASCAR Brasil." },
  { order: 56, name: "Bianca Chagas",                  handle: "@bianca.chagas",           slug: "bianca-chagas",         niches: ["Criptomoedas", "Investimentos"],                   followers: "10.3K",  engagement: "3.23%", platforms: ["Instagram"],                              color: "#E0F050", badges: [],             photoUrl: "/images/influencers/biancachagas.jpg",    bio: "3 anos de experiência no mercado cripto. Ensina seguidores a lucrar com criptomoedas. Criadora da comunidade Cripto Invest Pro. Crescimento de 24.90%." },
];

const FEATURED_SLUGS = ["ronaldinho-gaucho", "luva-de-pedreiro", "einerd", "lucao", "jon-vlogs", "inteligencia-ltda", "bambam", "baiano-lol"];
export const FEATURED_INFLUENCERS = FEATURED_SLUGS.map(
  (slug) => ALL_INFLUENCERS.find((i) => i.slug === slug)!
);

export const ALL_CASES = [
  {
    brand: "Nike",
    slug: "nike-lancamento-chuteiras",
    influencer: "Ronaldinho Gaúcho",
    result: "2M views em 24h",
    description: "Campanha de lançamento da nova linha de chuteiras com conteúdo exclusivo para Instagram e TikTok.",
    longDescription: "A Nike buscava um lançamento impactante para sua nova linha de chuteiras. Desenvolvemos uma estratégia de conteúdo exclusivo com Ronaldinho Gaúcho, criando uma série de vídeos que mostravam o ícone do futebol testando os novos produtos em cenários icônicos. A campanha gerou viralização orgânica massiva.",
    metric: "2M",
    metricLabel: "views em 24h",
    platforms: ["Instagram", "TikTok"],
    duration: "2 semanas",
    results: [
      { label: "Views totais", value: "8.5M" },
      { label: "Engajamento", value: "+420%" },
      { label: "Menções à marca", value: "15.2K" },
      { label: "Cliques no link", value: "340K" },
    ],
  },
  {
    brand: "Natura",
    slug: "natura-beleza-natural",
    influencer: "Juliette Freire",
    result: "+340% engajamento",
    description: "Série de conteúdos sobre beleza natural que gerou recorde de engajamento para a marca.",
    longDescription: "Para a Natura, criamos uma campanha focada em autenticidade e beleza natural com Juliette Freire. A série de conteúdos mostrava a rotina de cuidados da influenciadora usando produtos Natura, com um tom genuíno que ressoou profundamente com seu público.",
    metric: "+340%",
    metricLabel: "engajamento",
    platforms: ["Instagram", "YouTube"],
    duration: "1 mês",
    results: [
      { label: "Engajamento", value: "+340%" },
      { label: "Alcance", value: "12M" },
      { label: "Salvamentos", value: "890K" },
      { label: "Conversões", value: "+180%" },
    ],
  },
  {
    brand: "iFood",
    slug: "ifood-live-commerce",
    influencer: "Casimiro Miguel",
    result: "5M impressões",
    description: "Ação de live commerce com integração direta ao app, gerando conversões em tempo real.",
    longDescription: "O iFood queria explorar o formato de live commerce no Brasil. Desenvolvemos uma ação com Casimiro Miguel que integrava diretamente o app do iFood durante a transmissão ao vivo, permitindo que os espectadores fizessem pedidos em tempo real enquanto assistiam ao conteúdo.",
    metric: "5M",
    metricLabel: "impressões",
    platforms: ["YouTube", "TikTok"],
    duration: "1 semana",
    results: [
      { label: "Impressões", value: "5M" },
      { label: "Pedidos na live", value: "23K" },
      { label: "Pico de audiência", value: "185K" },
      { label: "ROI", value: "4.2x" },
    ],
  },
];
